#!/usr/bin/env node

/* eslint no-var: 0 */

console.log('Install database...')

var sqlite3 = require('sqlite3');
var db = new sqlite3.Database('botify-contest');

db.run('CREATE TABLE IF NOT EXISTS Users ( \
  name VARCHAR(50), \
  email VARCHAR(50), \
  language VARCHAR(10), \
  time SMALLINT, \
  code VARCHAR(1000) \
)');

db.close();
