#!/usr/bin/env node

/* eslint no-var: 0 */

var sqlite3 = require('sqlite3');
var db = new sqlite3.Database('botify-contest');

console.log('Install database...');

db.run('CREATE TABLE IF NOT EXISTS Users ( \
  id INTEGER PRIMARY KEY   AUTOINCREMENT, \
  name VARCHAR(50), \
  email VARCHAR(100), \
  language VARCHAR(10), \
  time SMALLINT, \
  code VARCHAR(2000) \
)');

db.close();
